# Generated by Django 3.1.5 on 2021-04-14 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={'managed': True},
        ),
    ]
