# Generated by Django 2.2.9 on 2021-03-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='tag',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
