# Generated by Django 3.1.5 on 2021-04-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20210414_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='sample',
            field=models.CharField(default='hello', max_length=20),
        ),
    ]
