# Generated by Django 3.1.5 on 2021-04-14 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_layer_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='sample',
        ),
    ]
