# Generated by Django 3.1.5 on 2021-04-14 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_remove_layer_sample'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'managed': True},
        ),
    ]
