# Generated by Django 3.1.5 on 2021-04-14 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_auto_20210414_0528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'managed': False},
        ),
    ]
