# Generated by Django 3.1.5 on 2021-04-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_layer_is_general'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'managed': True},
        ),
    ]
