# Generated by Django 3.1.5 on 2021-04-15 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0011_auto_20210415_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busstop',
            options={'managed': True},
        ),
    ]
