# Generated by Django 3.1.5 on 2021-04-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0012_auto_20210415_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='busstop',
            options={'managed': False},
        ),
    ]
