# Generated by Django 3.1.5 on 2021-04-19 10:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0013_auto_20210415_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerGeometryMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry_object', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('media', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='busstop',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='redline',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='layer',
            name='geometry_objects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.layergeometrymedia'),
        ),
    ]
