# Generated by Django 3.1.5 on 2021-04-19 10:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0014_auto_20210419_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='busstop',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='layergeometrymedia',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='redline',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='layergeometrymedia',
            name='geometry_object',
            field=django.contrib.gis.db.models.fields.GeometryField(dim=3, srid=4326),
        ),
        migrations.AlterModelTable(
            name='layergeometrymedia',
            table='geo_layergeometrymedia',
        ),
    ]
