# Generated by Django 3.1.5 on 2021-04-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0015_auto_20210419_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layergeometrymedia',
            name='media',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
