# Generated by Django 3.1.5 on 2021-04-19 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0016_auto_20210419_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='geometry_objects',
        ),
        migrations.AddField(
            model_name='layergeometrymedia',
            name='layer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.layer'),
        ),
    ]
