# Generated by Django 3.1.5 on 2021-04-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0017_auto_20210419_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='street',
            options={'managed': True},
        ),
    ]
