# Generated by Django 3.1.5 on 2021-04-19 10:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0018_auto_20210419_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='street',
            name='ogc_fid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
