# Generated by Django 3.1.5 on 2021-04-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0019_auto_20210419_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='media',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
