# Generated by Django 3.1.5 on 2021-04-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0020_street_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='busstop',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='redline',
            options={'managed': True},
        ),
    ]
