# Generated by Django 3.1.5 on 2021-04-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0022_auto_20210419_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model3DZip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('url', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'models_3d_zip',
                'managed': True,
            },
        ),
    ]
