# Generated by Django 3.1.5 on 2021-04-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0023_model3dzip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3dzip',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
